### ISSUE TITLE
CarPlay bug: after skipping songs, switching stations does not resync first station with master playlist

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#12]
Steps to reproduce:

1. Connect phone to vehicle and wait for CarPlay to engage.
2. Start RP, play a stream, and skip a bunch of songs (I did 5 songs within 30 seconds)
3. Switch to another station, wait for playback.
4. Switch back to the original station. 

Observed: the original station resumed playing the last song I was listening to.

Expected: the original station should "sync" with the master playlist online and play the song I would have been listening to had I *not* skipped over so many songs.

**Comment by RPNate1** [comment]
There was sync button on the old webplayer and we dropped it. I discussed this with William and we think we probably won't reinstitute the sync and certainly don't/shouldn't have the player resync as RP is a radio station and part of the music licensing as a radio station is that you can't go back in the playlist.

**Comment by bradtchapman** [comment]
Then how far ahead are music blocks programmed, and what happens if a user skips too far?

**Comment by bradtchapman** [comment]
Also, when the app is launched, it checks with the website to see what songs are playing at that moment.  There must be *some* master clock informing all clients what song is supposed to be playing and which block(s) to load.  In that sense, RP is still functioning as a radio station with clients "in sync," even if that station is fully automated.

**Comment by RPNate1** [comment]
The programming is essentially a GIANT looped playlist that gets adjusted/changed by William daily for the upcoming day(s).  We are not running blocks anymore. It's too buggy with trying to sync metadata with larger blocks. We moved over to gapless playback. 
After a timeout the apps will re-sync with the stream. There's an API call that checks in at the restart of play, whether it's from a pause or fresh start of the app. If paused, there's a specific timeout that SHOULD trigger syncing. It's wonky sometimes. We're actually discussing this internally to nail down how exactly we'd like it to function.

I think I got all that right...it's gets a bit out of my wheelhouse since I'm mostly a creative around here, relying on the dev to keep it all running. lol
