### ISSUE TITLE
[FR] show total time & songs in block

### ISSUE THREAD

**Issue by JohnADilley** [BillGoldsmith/iOS-bugfest#157]
## Brief description of the issue:
Download Manager shows progress and total size in number of songs.  It would
be great if total time were also available in that.

### Steps to reproduce:
Open Download Manager.  Load a cache block.  See "# songs in cache".

### Expected result:
In addition to number of songs, "# minutes of playback".

### Actual result:
Just number of songs.

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 62, iPhone Xs running iOS 16.2

**Comment by bradtchapman** [comment]
@JohnADilley : This may have changed permanently due to changes being made in the song retrieval API, but I agree that not knowing the total amount of time is a loss of functionality over RP v1.  The song count is more precise than total time and that is perhaps why they changed it.  

Tagging as feature request.

Maybe the download manager can check the song length *after* download and display a sum of the estimated play time of the block of music that was just retrieved.

**Comment by RPNate1** [comment]
Time will be implemented. Will tag this as such when I get over to Github
in a bit.

**Comment by donshefer** [comment]
implemented in build 66

**Comment by JohnADilley** [comment]
I see time now (but not number of songs). That's better (party with Mk1), and OK to close. Thank you.
