### ISSUE TITLE
Elements are missing in landscape mode on iPad 

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#172]
## Brief description of the issue:

Is this intentional or a bug? If you turn the iPad into landscape mode, several elements are missing, such as the number of comments and the lyrics display and the ratings function.

### Expected result:

Identical elements, regardless of whether portrait or landscape mode is selected

### Actual result:
Missing elements as described 

### Where did you see it? (App build version, device type and iOS version):
Build Mk2 09 (63), iPad Air (5th gen), iPadOS 16.5
![IMG_0827](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/388db176-2a48-424b-92f1-23cd363145fd)
![IMG_0826](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/093a2fc2-d308-445d-ba45-0c741592cceb)

**Comment by bradtchapman** [comment]
Confirmed.  Rotating an iPad mini 6th generation also results in elements being hidden, removed, or cut off the screen.

**Comment by bradtchapman** [comment]
The sudden shift happens quickly and not 100% of the time, as the app might be getting an early signal from a system framework about device orientation and adjusting mid-flight.  When it lags behind, that's when you can see the shift.  The app might have its own idea about where the elements need to go, overriding Apple's defaults.

These two stills were taken from a **slo-mo** movie.  It was necessary to film it this way because the 'Screen Recording' feature on the iPad made it impossible to reproduce the bug.  

![Screen Shot 2023-05-22 at 3 00 05 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/52c30c43-8879-4d67-88ea-bbac4cb34b37)

![Screen Shot 2023-05-22 at 3 00 11 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/f7918b2e-5293-4e01-9716-ebcd9c90fc44)

**Comment by bradtchapman** [comment]
Upgraded to P3 due to multiple elements missing: 

* share button
* lyrics
* comments
* heart vote

**Comment by JoschiW64** [comment]
Hi, on my iPad the error can be reproduced all the time, not just sometimes. I hope the short video helps.

I also noticed that the vertical three dots that are responsible for the download manager, the car mode and the timer, are also missing.

https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/4c5b1048-c8c3-4274-bc8d-e7b2827607d7

**Comment by RPNate1** [comment]
Confirmed on my iPad 8 as well. @donshefer let's scale the icons to the same height, as well

**Comment by donshefer** [comment]
The missing icons in landscape (share, lyrics, and comments) have been added to the three dots menu. The rating rating had been added to the bottom bar.
Updated in build 72

**Comment by RPNate1** [comment]
b72 fixed
