### ISSUE TITLE
[Bug] CarPlay sometimes only displays sync channel

### ISSUE THREAD

**Issue by zbartrout** [BillGoldsmith/iOS-bugfest#225]
## Brief description of the issue:
Sometimes when I plug my iPhone into my cars USB it only displays the sync channel and no other stations or cached stations 

### Steps to reproduce:
1. Plug iPhone in USB
2. Launch RP beta app
3. Access station list

### Expected result:
1. Was trying to access global mix

### Actual result:
1. Only sync channel displayed

### Where did you see it? (App build version, device type and iOS version):
Build 9(81) iPhone 13 Mini iOS 16.6

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
When was the last time you removed and installed the app fresh? I cleared up an issue yesterday by doing that. We've been pushing lots of updates and it's possible there was some corruption after many updates. @zbartrout

**Comment by donshefer** [comment]
This could happen if you don't have access to a network. It would only show you cached downloads. But, it shouldn't show the the option to sync. I will fix that.
Updated in build 82.

**Comment by zbartrout** [comment]
That's when it happens. Driving in the hills.

**Comment by RPNate1** [comment]
Can you validate that this is fixed @zbartrout ?

**Comment by zbartrout** [comment]
HiI am traveling right now and will not be able to confirm until next Tuesday. All best,ScottVia phoneScott Sayre Ed.D.| Chief Information Officer |Corning Museum of Glass | One Museum Way | Corning, NY 14830 | www.cmog.orgOffice: (607) 438-5298  |Cell: (612) 423-9691| Twitter: @zbartrout ***@***.*** On Jun 28, 2023, at 9:32 PM, RPNate1 ***@***.***> wrote:﻿
Can you validate that this is fixed @zbartrout ?

**Comment by RPNate1** [comment]
@bradtchapman you're my carplay guy this week...Please see if you can validate this fix. Force the phone off the network and see what happens. Shouldn't show sync. 
@donshefer should it show channels and give a notification that a network is needed? Not sure about the expected behavior of displayed channels.

**Comment by bradtchapman** [comment]
Observed the following behaviors:

When connected to CarPlay, if there is no signal when RP is launched—either a cold launch, or app was backgrounded by iOS a long time ago—the app will complain about no signal.  Additionally, the Channels list in CarPlay will be totally empty.  On the phone interface, the channel selector will show "Available Streams" and the only option will be "Download Manager."

If you then enable network connectivity enough for RP to discover the Internet, "Sync Current Channel" appears in the list above Download Manager.

If you try to play music, RP Main Mix loads.

In the CarPlay interface, it still shows the empty "Channels" screen (I suspect this page is not dynamically updated?) but the "Now Playing" arrow appears.  

If you tap the Now Playing arrow, it shows the RP album art and metadata for the current song.  If you tap "Back," you see the full list of channels, including "Sync Current Channel."  

Tapping "Sync Current Channel" in CarPlay loads the RP Main Mix.  Curiously, it also shows "Sync Current Ch..." in the Station selector on the phone.  

This "station" isn't really a station at all; its function is to refresh the active station.  That function is not working in CarPlay: when I tap Mellow Mix, then "Sync Current Channel," it switches back to Main Mix but shows "Sync Current Ch..." in the station selector on the phone.

In order to maintain maximum CarPlay functionality and avoid this specific issue, I would move the "sync" function out of the station list, like in the Kebab menu.  Recognizing that the kebab is quite full, I will point out that the Download Manager exists in two places now: the station selector, and the kebab menu.  

- Does the DL manager need to be in both places, or just one?
- Can DL manager live under the Profile / Settings menu since it's not used very often?
- Is the 'Info' button needed anymore?

If the Sync function intends to remain for CarPlay, then it needs to not appear in the Channels list — or it needs to not load RP Main Mix, but actually do what it says.  :-)

**Comment by bradtchapman** [comment]
Tagged as "Needs More Info" @RPNate1 or @donshefer .

**Comment by donshefer** [comment]
I have made a couple of changes. I have removed the Sync and Download Managed from the CarPlay channel list.
If there is no network, I would expect the CarPlay channel list to own show the downloaded blocks. If there is no network and no downloaded blocks, I would expect that list to be empty.
Updated in build 83

**Comment by RPNate1** [comment]
@bradtchapman check this and the other carplay issues that need validating please?

**Comment by bradtchapman** [comment]
@RPNate1 as soon as Build 83 hits TestFlight, I can.  :-)

**Comment by bradtchapman** [comment]
@RPNate1 : is this related to #239  ?

**Comment by zbartrout** [comment]
@donshefer @RPNate1 I have not seen this issue in the latest build. I will keep checking. I believe it is now working as @donshefer describes above.

**Comment by RPNate1** [comment]
fixed b83
