### ISSUE TITLE
seperate bitrates for wifi and cellular

### ISSUE THREAD

**Issue by jarro** [BillGoldsmith/iOS-bugfest#293]
This didn't work reliably in the past.   But that was years ago.

**Comment by RPNate1** [comment]
This has been requested a few times. i wonder if we could make it more stable now. @donshefer ?

**Comment by donshefer** [comment]
updated in v8.1.0 build 1021

**Comment by ChristianNoc** [comment]
Nice feature even if I don't need it because I have an excellent DataPlan all over Europe.

How can I easily test this feature? I would actually expect the actual sound quality to be displayed in the status bar under the play/pause button.

Every high quality player I know shows the actual sound quality in the main screen. Ok, maybe not Spotify, but any high resolution service or high resolution player. This can be important when you're on the road and have various roaming options out of the country.

@RPNate1  The selected or better the retrieved sound quality should be displayed as PlayStatus. Otherwise, this is error-prone.

**Comment by donshefer** [comment]
@ChristianNoc In settings, the app will display wifi or cellular after "Audio Settings" to let you know which you are current connected to. Changing the bitrate will affect that type of connection. If you want to switch from wifi to cellular, you can turn off wifi or cellular in control center. Songs will then be downloaded in that bitrate based on the current connection type.

**Comment by ChristianNoc** [comment]
@donshefer 
Yeah thanks that’s clear. I don’t trust settings without checking, so it would be helpful to see what the app is doing. You know most high res players or DA converter shows the signal quality when playing… it’s not really an issue for me but for people who has a limited cellular plan it could be a different story… especially when that feature wasn’t reliable in the old app as jarro mentioned…

**Comment by RPNate1** [comment]
fixed in 8.1
