### ISSUE TITLE
airplay apple tv

### ISSUE THREAD

**Issue by jarro** [BillGoldsmith/iOS-bugfest#299]
Had a few airplay complaints specific to apple tv.

**Comment by jarro** [comment]
Since the last major update, Airplay does not work anymore. The device on the other end (Apple TV)  recognizes it’s being called, but the music does not go through.
Always worked without a problem. Pity right now, because this is the (only) way I listen to Radio Paradise.
My phone: iPhone 12 mini.

**Comment by jarro** [comment]
iOS App Version 8 / Problems with AirPlay

Hello,
I experience problems with Air Play with the latest Update.
I can choose an AppleTV as a receiver but theres´s no Sound then.
I shows "playing" but nothing happens.
(AirPlay is working with Apple Music)
Can anyone help ?

Greetings from Germany

**Comment by donshefer** [comment]
I think I have found the issue. There was a very counter intuitive flag that seems to have needed to be set, "player.allowsExternalPlayback = false" in order to get AppleTV to work properly. I confirmed that the prior version of the app had this set to false.
Evidently, this block *video* playback so that audio works properly. 🤦🏻 
Updated in version 8.0.2 build 1016.

**Comment by k00ka** [comment]
Works on my setup. ATV2(HD) with build 1015. So I guess my setup just somehow works.

**Comment by RPNate1** [comment]
fixed
