### ISSUE TITLE
UI bug (b29): login window is cramped on smallest screens

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#38]
![63DC6526-56DA-4B86-B84A-6CFD683C7342](https://user-images.githubusercontent.com/32527656/216758632-b75a0434-3cc0-4316-8d90-ea6acc19f491.png)

This was taken on an iPhone SE @ 15.7.3.  4” screen.  loads of people still have these devices and they run iOS 15.

The RP logo is up in the status bar, and the listen anonymously link is so close to the bottom that tapping it sometimes causes iOS to think I want to swipe up for Control Center.  

On devices with Touch ID, control center is a swipe up from the bottom.  Starting with IPhone X,   devices with Face ID have control center swipe down from the top right corner.

**Comment by donshefer** [comment]
Updated and tested on an iPhone SE Gen 3.
Please note, the app won't support SE Gen 1 or 2. Our target deployment versions is 15.5 because of the SwiftUI.
@bradtchapman If you are running build 41 on a Gen1 SE then please let me know. I may have missing something. SwiftUI is buggy going back past 15.5.
Targeting build 41

**Comment by bradtchapman** [comment]
I updated the iPhone SE 1st gen to a compatible version of iOS: 15.7.3.  I have been testing the RP app on that version for several weeks.

-Brad


—Sent from my iPhone
