### ISSUE TITLE
UI suggestion: add zone for "tap to scroll up" for very long pages

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#43]
### Description

I'd like a way to quickly scroll back to the top, just like in Safari, where you tap the very top edge of the screen and it jumps to the top.

### Workaround 

Currently a user would have to manually scroll up for eternity, or tap the song info bar again.  The second action has the intended effect, but is not an intuitive action.

iOS should have a mechanism for creating a tap zone near the top that tells another view to scroll up.  You might need to decrease the tap zone or size of the RP logo depending on testing and implementation.

![1FF2A7CE-3B85-4BD1-AA24-83F3FEEADCB8](https://user-images.githubusercontent.com/32527656/216792300-d5d346c8-a7b0-42bd-bedd-1df3a6293d1c.jpeg)

**Comment by RPNate1** [comment]
@donshefer ? thoughts?

**Comment by bradtchapman** [comment]
This might be a @jarro question too, because I cannot tap to scroll to the top of the RP site either.

**Comment by donshefer** [comment]
We can listen for taps outside the webview to scroll inside the webview, but that is going require a function in the javascript to do communicate that back into the web app. There is also a bit of a conflict because the logo at the top opens the website. And the tappable area above that is the status bar, which usually isn't tappable without overriding the OS. 
I don't really see this as good UI. And I don't think iOS user are going to expect that behavior.

**Comment by bradtchapman** [comment]
The "scroll to top" zone isn't where the logo is.  It's at the extreme top end above the logo. People usually tap the face ID sensor itself and iOS knows that they intend to scroll up.  

The tap zone for the logo should not extend to the very top of the screen anyway.


—Sent from my iPhone
