### ISSUE TITLE
Strange playback behavior on car bluetooth when force closing app

### ISSUE THREAD

**Issue by RPNate1** [BillGoldsmith/iOS-bugfest#93]
The playback was behaving strangely while I was connected to the Bluetooth in my car. 

I force quit all my apps and RP mk2 restarted in the background by itself. It was not visible as an active app even though it was playing music. 

I clicked on the app icon and it popped up as though it had been open the whole time. I forced it closed and reopened it several times.
The first time it resumed play as expected. 
The next couple of times it appeared to jump ahead in the track by about 30 secs. 
Then it started the next track. I closed it out and restarted it again, this time it jumped ahead again. 
Forced it closed again and when I restarted it, it jumped back a track. 
Forced it closed again and reopened. This time it was back on the next track at the beginning. 
Then upon another force close and reopen it seemed to jump ahead by 30 or so seconds again.

I realize this isn't the best bug report but something was definitely not acting right. I was trying to drive and didn't want to get into a wreck trying to properly document...

**Comment by bradtchapman** [comment]
RP might be starting because it was last used for "Now Playing."

In iOS, it's generally true that if music was playing before connecting to a Bluetooth speaker, it will resume playback once the speaker is connected.  

I suspect your car stereo is triggering RP to start playing.  

Questions:
1. What kind of car do you drive, @RPNate1 ? 
2. Is it the factory radio, or aftermarket?
3. If aftermarket, what make / model?
4. Does your car radio support CarPlay or just Bluetooth?
5. Have you tested this with the Apple Music or Spotify app?
6. Have you tested this with a Podcasting app like Overcast?
7. Have you tested this with SomaFM, which uses a different playback mechanism?
8. Have you tested this behavior with RPv1?

It's too bad Siri won't accept "Hey Siri, start recording my screen" (already tried; it's not allowed).  Next time, though, you could add "Screen Recording" to your Control Center and start recording one on the road by swiping to open Control Center and just tapping on the button.  I've been using this feature all the time.

Note: for some silly reason, Apple doesn't allow you to record the screen while using CarPlay in a real car; you have to use the Xcode CarPlay simulator for that, which isn't a great test environment. Regular Bluetooth speaker connections won't be a problem for making screen recordings.

**Comment by RPNate1** [comment]
1. 2018 Mazda3
2. factory
3. na
4. BT
5. Spotify, all the time. Works fine.
6. nope. don't listen to podcasts currently
7.  nope
8. I never use RPmk1

I'm fine with my car restarting playback. I just want it to play back the proper tracks. It was definitely not doing that. It moved forward through tracks for no good reason. Jumped back a track and then resumed what should have been the proper track, but skipped through it rather than starting from the position it was at when closed.

**Comment by bradtchapman** [comment]
Maybe it's related to #94 .

**Comment by RPNate1** [comment]
I haven't been able to recreate this with the newest build, b37

**Comment by bradtchapman** [comment]
@RPNate1 : me either.  My 2004 VW Beetle has an upgraded Alpine car stereo with Bluetooth and it behaves as expected.
